### ISSUE TITLE
Create a dynamic memory allocator for the kernel

### ISSUE THREAD

**Issue by mdpcs3544** [CharlotteOS-Deprecated/charlotte-core#123]
Create a dynamic allocator for the kernel that implements the zenalloc Allocator trait to allow the kernel to dynamically allocate and deallocate memory.

- [x] Extend the VMM to be able to determine if a region of the higher half is available or in use by walking the kernel-only page map.
- [ ] Add the ability to map and allocate buffers that are a single page or larger in size.
- [ ] Add the ability to deallocate and eagerly unmap buffers that are a single page or larger in size.
- Create a subpage allocator the primary allocator which can only allocate in multiples of pages (of any combination of sizes)
    - [ ] Allocate a stack to store the addresses of subpage allocation regions (9 pages each; 1 bitmap and 8 usable memory)
    - [ ] Add the ability to make subpage allocations
    - [ ] Add the ability to free subpage allocations
- [ ] Implement the Allocator trait.

**Comment by mdpatelcsecon** [comment]
Need to add a means of using the current implementation of the MemoryMap trait to the ArchApi and then creating a wrapper under `crate::memory` with extra functionality such as map contiguous to that wrapper using the underlying trait from ArchApi.

**Comment by mdpcs3544** [comment]
I am considering implementing this as a library crate that can be used in both kernelspace and userspace and only relies on having a fixed region of memory which can be grown or shrunk by calling client provided function pointers.

**Comment by mdpcs3544** [comment]
The MemoryMap trait in arch has been expanded to be able to scan a region of a memory map to be able to find a free region of a given size and alignment if there is one. This functionality has also been implemented in the x86_64 VMM. 

This is the first step in implementing dynamic memory allocation for Charlotte Core itself. The next step is will be to implement the actual function that actually uses this new functionality to allocate larger than page sized memory buffers for the kernel.
